name: "Github CI"
on:
  push:
    branches:
      - master

jobs:
  build-release-archive:
    name: Build release archive
    runs-on: windows-2022

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      - name: Make release archive
        shell: cmd
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=amd64 -host_arch=amd64 &&^
          nmake BUILD_MODE=Release dist
      - name: Upload release archive
        uses: actions/upload-artifact@v4
        with:
          name: release-archive
          path: dist_out/*.zip
          if-no-files-found: error
          compression-level: 0