name: "Github CI"
on:
  push:
    branches:
      - master

jobs:
  build-release-archive:
    name: Build release archive with "make_release.ps1"
    runs-on: windows-2022

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      - name: Make release archive (Windows PowerShell)
        shell: cmd
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=amd64 -host_arch=amd64 &&^
          powershell.exe -ExecutionPolicy Bypass -File .\make_release.ps1
